version: 2.1

orbs:
  node: circleci/node@5.0.0
  deploy: circleci/github-cli@2.2.0

jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies
      - run: npm install

      # Build website
      - run: npm run build

  deploy:
    docker:
      - image: circleci/python:3.8.1

    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}

    steps:
      - checkout

      # Install gh-pages and dependencies
      - run: pip install ghp-import

      # Deploy website to GitHub Pages
      - run: ghp-import -n -p -f ./build

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
