version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - build
